#!/usr/bin/env bash

set -e

pacman -Syu --needed --noconfirm docker

[[ -n "$(vgs)" ]] && vgs --noheadings -o vg_name | xargs -n1 vgremove -f
[[ -n "$(pvs)" ]] && pvs --noheadings -o pv_name | xargs -n1 pvremove -f

pvcreate /dev/xvdd
vgcreate dock0 /dev/xvdd

lvcreate -L 10G -Wn -n tmp dock0
mkfs.ext4 /dev/dock0/tmp
mkdir -p /var/lib/docker
mount /dev/dock0/tmp /var/lib/docker
systemctl start docker

mkdir -p /run/vm/bootmnt
mount /dev/xvdc /run/vm/bootmnt
docker run -ti -v /run/vm/bootmnt:/run/vm/bootmnt dock0/vm_install

docker run -ti -v /run/vm/bootmnt:/run/vm/bootmnt -p 1001:22 -p 1002:80 dock0/vm_config

shutdown now

